-- =====================================================================
-- Urban Intelligence Platform — Turso (libSQL) schema
-- =====================================================================
-- One table holds every detected "issue" event reported by the bus/CCTV
-- fleet (or, for now, seeded fake data). The AI agent that will run in
-- production is expected to INSERT new rows as detections happen and
-- DELETE rows once an issue is resolved / expires / is a false positive.
-- =====================================================================

CREATE TABLE IF NOT EXISTS events (
  id              TEXT PRIMARY KEY,      -- uuid, generated by whoever inserts
  category        TEXT NOT NULL,         -- pothole | road_damage | missing_zebra |
                                          -- signboard | waterlog | crossing_alert | congestion
  lat             REAL NOT NULL,
  lng             REAL NOT NULL,
  confidence      INTEGER NOT NULL,      -- 0-100, model confidence
  severity        TEXT NOT NULL,         -- Low | Medium | High
  bus_id          TEXT NOT NULL,         -- e.g. BUS-014, the reporting vehicle
  image_url       TEXT,                  -- fake for now, later a real hosted photo
  status          TEXT NOT NULL DEFAULT 'active',  -- active | resolved | false_positive
  detected_at     TEXT NOT NULL,         -- ISO 8601 timestamp of detection
  created_at      TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_events_category   ON events(category);
CREATE INDEX IF NOT EXISTS idx_events_status     ON events(status);
CREATE INDEX IF NOT EXISTS idx_events_detected   ON events(detected_at);
CREATE INDEX IF NOT EXISTS idx_events_bus        ON events(bus_id);

-- Optional: fleet/bus registry, useful once real buses report in.
CREATE TABLE IF NOT EXISTS buses (
  bus_id          TEXT PRIMARY KEY,
  status          TEXT NOT NULL DEFAULT 'active',  -- active | offline | maintenance
  last_seen_at    TEXT,
  last_lat        REAL,
  last_lng        REAL
);
